---
- name: Installation & Konfiguration
  hosts: nginx
  become: yes
  tasks:
    - name: Install Nginx
      apt: 
        name: nginx
        state: present

    - name: Change Nginx Port to 9091 IpV4
      Lineinfile:
        path: /etc/nginx/sites-enabled/default
        regexp: 'Listen\s+80\s+default_server;'
        line: 'Listen 9091 default_server;'
        state: present
        backup: yes

      - name: Ensure Nginx is started and enabled
        service: 
          name: nginx
          state: started
          enabled: yes

